---
title: "R for geographers – Introductory course"
output: github_document
---

<br>  
  
This course is open for all geographers working at the department and interested in learning how to work with R. In this introductory course, some R basics will be taught on a step-by-step basis. Bring your own laptop, there will be exercises. No prior knowledge is needed.
<br>  

**Proposed date:** 28th of March  
**Proposed schedule**

- 9:00 to 10:00 - **Basic R** (1,2,3)
- 10:00 to 10:15 - Coffee Break
- 10:15 to 12:00 - **Importing Data and the tidyverse** (4,5)
- 12:00 to 12:45 - Lunch Break
- 12:45 to 14:00 - **Data.Table and speeding up your code** (6,7)
- 14:00 to 15:00 - **Sf, Shiny and Leaflet** (8)
- 15:00 to 15:15 - Coffee Break
- 15:15 to 16:00 - **Test your data and Q&A**

**Proposed place: S8** – PC-lokaal 0.1 Victor Van Straelen  
**Course registration:** https://goo.gl/forms/LbEs9fIwxuMdGXtI2  
**Teachers:** Filipe Marques Teixeira, Jeffrey Verbeurgt, Tom Storme  
<br>  

Please bring your own laptop, and install R and RStudio prior to the session. Datasets will be available here beforehand.
Participants are expected to arrange their own food/drinks. There are vending machines along with a student restaurant nearby. We'll upload a schedule as soon as possible.
You can download R and RStudio here https://www.rstudio.com/products/rstudio/download/#download. After downloading and installing R, please install the packages below.

```{r eval=FALSE}
install.packages(c("data.table", "tidyverse", "shiny", "leaflet", "lubridate", "igraph", "tidyr", "sf", "sp", "rgdal"))
```
<br>  

### Proposed program
1. **Getting Started**
-	Why use R?
-	Why use Rstudio
-	Basic R syntax
-	Write your first script  

2. **First programming with R**
-	R is vector-based (!)
-	R functions
-	R packages
-	Basic Arithmetic, Indexing, Comparing values
-	Tips and tricks (Code structure and conventions)  

3. **More Programming with R**
-	Naming values in a vector
-	Working with text values
-	R objects (factors, matrix, data frame, list, tibble)
-	If-else, for-loops and switch()
-	One big apply-family  

4. **Importing and writting data**
-	Load flat files using base R functions
-	readr & data.table (fread, fwrite)
-	Import and manipulate Excel-files
-	RDS and RDA

5. **Tidyverse for proper data science**
-	dplyr and piping
-	lubridate (dates), stringr (strings)
-	tidyr
-	ggplot2

6. **data.table**
-	DT[i, j, by]
-	Operations in i and operations in j
-	Select, subset, group, order, create
-	.N and other special operators  

7. **Increase Speed**
-	using dplyr and data.table together
-	why you shouldn’t use SQL

8. **Showing off with R**
-	Reports with R markdown
- leaflet and sf (geocomputation package)
-	Interactive visuals with Shiny
-	Introduction to network analysis with igraph


#### Extra Data to download
https://www.dropbox.com/sh/0l8m6mkor9wlmk4/AADqdC7pu66TlARCij0iUSkRa?dl=0